#################################################
# SMT Playbooks: Initial Server Setup
#################################################

# Run on Mac OS: (https://github.com/ansible/ansible/issues/76322)
# export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# ansible-playbook -i hosts.ini setup-new-instance-playbook.yml
---
- name: Setup Ubuntu Server
  hosts: sample_server
  become: true
  roles:
    - ngtrieuvi92.setup_ubuntu_sever
  vars:
    target_user: rin
    ssh_public_key_paths:
      - ~/.ssh/id_rsa.pub
